sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_script:
  - npm prune
after_success:
  - [[ $TRAVIS_BRANCH == 'master' ]] && npm run build && npm run deploy
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
